// SPDX-License-Identifier: CC-BY-4.0
//
// riscv-platform-spec.adoc: main file for the specification
//
// This file provides the primary structure and formatting for
// the overall Profile and Platform Specification.
//
= RISC-V Platform Specification
:author: RISC-V Platform Specification Task Group
:email: tech-unixplatformspec@lists.riscv.org
:revnumber: 0.2-rc0
:revdate: Apr 2021
:doctype: book
:sectnums:
:sectnumlevels: 5
:toc: macro
:toclevels: 5

// table of contents
toc::[]

// document copyright and licensing information
include::licensing.adoc[]

// changelog for the document
include::changelog.adoc[]

// Introduction: describe the intent and purpose of the document
include::introduction.adoc[]

// Profiles: (NB: content from very first version)
include::profiles.adoc[]

// Linux-2022 Platform
== Linux-2022 Platform

=== Terminology
[cols="1,2", width=80%, align="left", options="header"]
|===
|TERM      | DESCRIPTION 
|SBI       | Supervisor Binary Interface    
|UEFI      | Unified Extensible Firmware Interface
|ACPI      | Advanced Configuration and Power Interface
|SMBIOS    | System Management Basic I/O System
|DTS       | Devicetree source file    
|DTB       | Devicetree binary
|RVA22     | RISC-V Application 2022
|EE        | Execution Environment
|RV32GC    | RISC-V 32-bit general purpose ISA described as RV32IMAFDC.
|RV64GC    | RISC-V 64-bit general purpose ISA described as RV64IMAFDC.      
|===

=== Specifications
[cols="1,2", width=80%, align="left", options="header"]
|===
|SPECIFICATION      | VERSION 
|link:https://uefi.org/sites/default/files/resources/UEFI_Spec_2_9_2021_03_18.pdf[UEFI Specification]         | v2.9    
|link:https://github.com/devicetree-org/devicetree-specification/releases/tag/v0.3[Devicetree Specification]  | v0.3
|link:https://github.com/riscv/riscv-sbi-doc/blob/master/riscv-sbi.adoc[SBI Specification]                    | v0.3-rc0
|link:[RVA22 Specification]                                                                                   | TBD
|link:https://arm-software.github.io/ebbr/[EBBR Specification]                                                | v2.0.0-pre1    
|link:https://uefi.org/sites/default/files/resources/ACPI_Spec_6_4_Jan22.pdf[ACPI Specification]              | v6.4
|link:https://www.dmtf.org/sites/default/files/standards/documents/DSP0134_3.4.0.pdf[SMBIOS Specification]    | v3.4.0
|link:[Platform Policy]                                                                                       | TBD
|===

// Base feature set for Linux-2022 Platform
=== Base
==== Architecture
* Profile - RVA22
** Cache Management
** PMU 
** ASID 
* Debug

==== Memory Map
* Virtual Memory
* sv39/sv48/sv57
* Start Address

==== Interrupt Controller
* AIA
* PLIC + CLINT
* Interrupt Assignments

==== System Peripherals
* UART/Serial Console

In order to facilitate the bringup and debug of the low level initial platform
software(firmware, bootloaders, kernel etc), platforms are required to
implement a UART port which confirms to the following requirements:

* The UART register addresses are required to be aligned to 4 byte boundaries.
If the implemented register width is less than 4 bytes then the implmented
bytes are required to be mapped starting at the smallest address.
* The UART port implementation is required to be register-compatible with one
of the following:
** UART 16550 - _REQUIRED_
** UART 8250 - _DEPRECATED_

* Clock and Timers
** Platforms are required to provide an at least 10ns resolution 64-bit counter
with strictly monotonic updates.
** The hardware clock that drives the counter is required to operate at a minimum
frequency of 10MHz.
** Platforms that use DT for hardware discovery are required to advertise the
timebase to the operating systems via the `timebase-frequency` property of the
"/cpus" node
footnote:[https://elixir.bootlin.com/linux/latest/source/Documentation/devicetree/bindings/riscv/cpus.yaml].

[sidebar]
--
[underline]*_Implementation Note_*

For a counter with 10ns resolution the `timebase-frequency` value would be 100000000
(100 MHz) which would also be the minimum possible value for `timebase-frequency`.
From the software perspective a unit increment of the mtime value would correspond
to a 10ns interval. However the hardware clock driving the counter could operate at a
lower frequency, thereby incrementing the mtime value by more than one unit per
clock tick.
--
==== Boot Process
- The base specification defines the interface between the firmware and the 
operating system suitable for the RISC-V platforms with rich operating 
systems.
- These requirements specify the required boot and runtime services, device 
discovery mechanism, etc. 
- The requirements are operating system agnostic, specific firmware/bootloader
implementation agnostic.
- Any RV32GC or RV64GC platform seeking compatibility with the base 
specification is required to implement all three privilege modes i.e. M, S and
U mode.
- For the generic mandatory requirements this base specification will refer to
the EBBR Specification. Any deviation from the EBBR will be explicitly 
mentioned in the requirements.
- Specifications followed are mentioned in the  
<<Specifications,Specification Section>>


===== Firmware
====== Storage and Partitioning
- GPT partitioning required for shared storage.
- MBR support is not required

===== Discovery Mechanisms 
- Device Tree (DT) is the required mechanism for system description.
- Compliance with the System Description Specification is required – TBD


==== Runtime Services
===== SBI

- Required SBI spec version is 0.3 or higher.
- Required SBI extensions -

[cols="1,2", width=80%, align="left", options="header"]
|===
|EXTENSION     |    CONDITIONS 
|SBI TIME      |    if **stimecmp** CSR not available
|SBI IPI       | 
|SBI RFENCE    | 
|SBI HSM       | 
|SBI SRST      |    
|SBI PMU       | 
|===

- Required responsibilities of M-Mode runtime also includes - 
    ** Interrupt and Exception Delegation
    ** Misaligned Load & Stores handling
    ** Missing CSRs emulation 
    ** PMP Configuration

- Wherever applicable firmware must implement UEFI interfaces over similar 
interfaces and services present in the SBI specification. For example, UEFI 
runtime services must implement ResetSystem() via SBI Reset extension. 

===== UEFI
- OS should prioritize calling the UEFI interfaces before the SBI or Platform 
specific mechanisms.

// Server extension for Linux-2022 Platform
=== Server Extension
The server extension specifies additional  requirements apart from base
requirements for RV64I based server class platforms.

The platforms which conform to server extension are required to implement

- Advanced Platform-Level Interrupt Controller (APLIC). [*Dependency:
 AIA spec should be ratified*]
- Incoming MSI Controller (IMSIC) [*Dependency: AIA spec should be
ratified*]

- RISC-V Hypervisor-level Instruction-Set Extensions. [*Dependency:
Spec should be ratified*]
- Incoming MSI Controller (IMSIC) with at least 1 guest interrupt
file for each HART ?? (*TBD*)
- IOMMU with support for memory resident interrupt files ?? (*TBD*)

==== Boot and Runtime Requirements
=====  Firmware
The boot and system firmware for the RV64I server platforms required to be
based on UEFI as per the base specification with some additional
requirements as mentioned below.

====== PCIe support
The platforms are required to implement *EFI_PCI_ROOT_BRIDGE_IO_PROTOCOL* and other
protocols as specified in Chapter 14 of UEFI specification version 2.9.

====== UEFI configuration tables
The platforms are required to provide following tables.

* *EFI_ACPI_20_TABLE_GUID* ACPI configuration table which is at version 6.4+ or
newer with HW-Reduced ACPI model.
* *SMBIOS3_TABLE_GUID* SMBIOS table which conforms to version 3.4 or later.

====== UEFI Protocol support
The UEFI protocols listed below are required to be implemented in addition to
the base spec requirements.

.Required UEFI Protocols
[cols="3,1,1", width=95%, align="center", options="header"]
|===
|Protocol                              | UEFI 2.9 $ | Note
|EFI_LOAD_FILE2_PROTOCOL               | 13.2       |
|EFI_DECOMPRESS_PROTOCOL               | 19.5       |
|===

===== Hardware Discovery Mechanisms

====== ACPI

For RV64I server platforms, ACPI tables are required to be passed via UEFI
to the operating system for the purpose of discovery and the configuration of
the hardware. This section defines the required ACPI tables and objects. All
other ACPI tables for RISC-V can be implemented as needed adhering to the ACPI
spec version 6.4+(RISC-V support when added).

In ACPI namespace, processors are required to be defined under the System Bus
*(\_SB)* name space.

The required ACPI System Description Tables, Device Objects and Methods are
listed below.

.Required ACPI System Description Tables
[cols="3,1,2", width=95%, align="center", options="header"]
|===
|ACPI Table                                    |ACPI 6.4+ $|Note
|Root System Description Pointer (RSDP)        |5.2.5      |
|Extended System Description Table (XSDT)      |5.2.8      |
|Fixed ACPI Description Table (FADT)           |5.2.9      |
|Differentiated System Description Table (DSDT)|5.2.11.1   |
|Multiple APIC Description Table (MADT)        |5.2.12     |*TBD*: Need ECR
                                                            to add
                                                            APLIC & IMSIC
                                                            (AIA) to MADT
|RISC-V Timer Description Table                |New        |*TBD*: _DSD to
                                                            communicate
                                                            timebase-frequency?
|Processor Properties Topology Table (PPTT)    |5.2.29     |CPU/Cache topology
                                                            information
|Memory-mapped ConFiGuration space (MCFG)      |PCI-SIG    |Required for PCIe
                                                            support
|Debug Port Table 2 (DBG2)                     |Microsoft  |*TBD*: 16550D?
|Serial Port Console Redirection (SPCR)        |Microsoft  |*TBD*: 16550D?
|System Resource Affinity Table (SRAT)         |5.2.16     |Required if the
                                                            platform supports NUMA
|System Locality Information Table (SLIT)      |5.2.17     |Required if the
                                                            platform supports NUMA
|IOMMU Information Table                       |           |*TBD*: New IOMMU
                                                            table need to be
                                                            defined (like IVRS)
|Software Delegated Exception Interface (SDEI) |SDEI       |*TBD*: New table
                                                            and SBI extension
                                                            also may be required
|PMU event mapping table?                      |New        |*TBD*: New table
                                                            required
|===


.Required Device Objects and Methods
[cols="1,2,3", width=95%, align="center", options="header"]
|===
|Object/Method | ACPI 6.4+ $ | Note
|_AEI          | 5.6.5.2     | Required for GPIO-signalled events.
|_EVT          | 5.6.5.3     | Required for interrupt-signalled events.
|_ADR          | 6.1.1       | Required for PCI
|_HID          | 6.1.5       |
|_UID          | 6.1.12      |
|_CRS          | 6.2.2       |
|_CCA          | 6.2.17      | Required for DMA capable devices
|_STA          | 6.3.7/7.2.4 | Device status
|===

====== SMBIOS

The System Management BIOS (SMBIOS) table is required for the platform
conforming to server extension. The SMBIOS records provide basic hardware and
firmware configuration information used widely by the platform management
applications.

The SMBIOS table is identified using *SMBIOS3_TABLE_GUID* in UEFI configuration
table. The memory type used for the SMBIOS table is required to be of type
*EfiRuntimeServicesData*.

In addition to the conformance guidelines as mentioned in *ANNEX A / 6.2* of
the SMBIOS specification 3.4.0, below additional structures are required.

.Required SMBIOS structures
[cols="4,1,2", width=95%, align="center", options="header"]
|===
|Structure Type                                 | SMBIOS 3.4.0 $ | Note
|Management Controller Host Interface (Type 42) | 7.43           | Required for
Redfish Host Interface.
|Processor Additional Information (Type 44)     | 7.45           | This
structure provides the additional information of RISC-V processor
characteristics and HART hardware features discovered during the firmware boot
process.
|===

===== Boot-Loader
*TBD*

===== Runtime services
====== SBI
*TBD*

====== UEFI
The UEFI run time services listed below are required to be implemented.

.Required UEFI Runtime Services
[cols="3,1,3", width=95%, align="center", options="header"]
|===
|Service                   | UEFI 2.9 $ | Note
|GetVariable               | 8.2        |
|GetNextVariableName       | 8.2        |
|SetVariable               | 8.2        | A dedicated storage for firmware is
required so that there is no conflict in access by both firmware and the OS.
|QueryVariableInfo         | 8.2        |
|GetTime                   | 8.3        | RTC Access by the OS
|SetTime                   | 8.3        | If it is not possible to set the RTC,
the SetTime() can return an error.
|GetWakeupTime             | 8.3        | Interface is required to be
implemented but it can return EFI_UNSUPPORTED.
|SetWakeupTime             | 8.3        | Interface is required to be
implemented but it can return EFI_UNSUPPORTED.
|SetVirtualAddressMap      | 8.4        |
|ConvertPointer            | 8.4        |
|GetNextHighMonotonicCount | 8.5        |
|ResetSystem               | 8.5        | If SBI SRST implementation is
also available, the OS should not use the SBI interface directly but use this
UEFI interface.
|UpdateCapsule             | 8.5        | Interface is required to be
implemented but it can return EFI_UNSUPPORTED.
|QueryCapsuleCapabilities  | 8.5        | Interface is required to be
implemented but it can return EFI_UNSUPPORTED.
|===

==== System Peripherals
* Clock and Timers
** Platforms are required to implement the time CSR.
** Platforms are required to implement the
https://lists.riscv.org/g/tech-privileged/message/404[Sstc] extension.
** Platforms are required to delegate the supervisor timer interrupt to 'S'
mode. If the 'H' extension is implemented then the platforms are required to
delegate the virtual supervisor timer interrupt to 'VS' mode.
* PCI-E

==== Secure Boot
* TEE
* Root of Trust
* E-Fuse
* PKA/TRNG

==== Virtualization/Hypervisor
* H-extension
* IOMMU

==== RAS

// Embedded-2022 Platform
== Embedded-2022

=== Scope
The Embedded-2022 specification aims to apply to a range of embedded platforms.
In this case embedded platforms range from hand coded bare metal assembly
all the way to to embedded operating systems such as
https://www.zephyrproject.org[Zephyr] and embedded Linux.

This specification has two competing interests. On one hand embedded software
will be easier to write and port if all the embedded hardware is similar. On
the other hand vendors want to differentiate their product and reuse existing
IP and SoC designs.

Due to this, the Embedded-2022 specification has both required and recommended
components. All required components must be met in order to meet this
specification.
It's strongly encouraged that all recommended components are met as well,
although they do not have to in order to meet the specification.

=== Base
==== Architecture
The Embedded-2022 specification depends on the RVM22 specification and all
requirements from RVM22 must be met.

Any RISC-V system that uses at least RV32/64G can meet the Embedded-2022
specification.

==== Interrupt Controller
Embedded systems are recommended to use a spec compliant
https://github.com/riscv/riscv-plic-spec[PLIC], a spec compliant
https://github.com/riscv/riscv-fast-interrupt/blob/master/clic.adoc[CLIC]
or both a CLIC and and PLIC.

If using just a PLIC the system must continue to use the original basic
`xsip`/`xtip`/`xeip` signals in the `xip` register to indicate pending
interrupts.
If using the CLIC then both the original basic and CLIC modes of interrupts
must be supported.

Embedded systems cannot use a non-compliant interrupt controller and still
call it a PLIC or CLIC.

==== Machine Timer
The RISC-V machine timer (controlled via `mtime` and `mtimecmp`) must be
implemented. The two registers must be memory mapped as required by the RISC-V
specification.

The Embedded-2022 specification requires that the registers be mapped
adjacent to each other with the `mtime` region at the lower address.

The starting address of this region can be located anywhere in
memory, including inside other peripherals, as long as the start address is
4 byte aligned.

An example of the memory layout for a 32-bit system with a single hart is below

-------------------------
=========================
| 0x00 |  mtime low     |
| 0x04 |  mtime high    |
| 0x08 |  mtimecmp low  |
| 0x0C |  mtimecmp high |
=========================
-------------------------

and for a 64-bit system with 2 harts

---------------------------
===========================
| 0x00 |  mtime           |
| 0x08 |  mtimecmp hart 1 |
| 0x10 |  mtimecmp hart 2 |
===========================
---------------------------

==== Memory Map
It is recommended that main memory and loadable code (not ROM) start at
address `0x8000_0000`.

// PMP extension for Embedded-2022 Platform
=== Physical Memory Protection (PMP) Extension
It is recommended that any systems that implement more then just machine mode
also implement PMP support.

When PMP is supported it is recommended to include at least 4 regions, although
if possible more should be supported to allow more flexibility. Hardware
implementations should aim for supporting at least 16 PMP regions.

// acknowledge all of the contributors
include::contributors.adoc[]
