# RISC-V Operating System Platform Specification
:author: RISC-V Platform Specification Task Group
:email: tech-unixplatformspec@lists.riscv.org
:revnumber: 0.1-draft1
:revdate: September 2020
:revremark: Initial draft.
:doctype: book
:sectnums:
:toc: macro

// Table of Contents
toc::[]

// Overall document copyrights and licensing
include::licensing.adoc[]

// Document contributors
include::contributors.adoc[]

// Changelog
include::changelog.adoc[]

// Begin the really interesting parts of the document
## Introduction

This document is the RISC-V Operating System Platform Specification
(OSPS).  This specification defines the hardware and firmware
required to be able to install and use one or more operating systems on a
platform built around the RISC-V Instruction Set Architecture (ISA).
The intent is to set out the constraints necessary
for a hardware platform so that an operating system can be assured
it is compatible with that platform, if the platform is in compliance
with this specification.

This specification also sets out the constraints on the
RISCV-V Instruction Set Architecture (ISA) -- at all privilege 
levels -- that are needed to provide a consistent and predictable
environment for running these operating systems.

The OSPS sets out the constraints on platforms as _use cases_.  Each
use case specifies a particular combination of hardware platform
and operating system to be used in specific environments.  For example,
the general purpose computing use case specifies the expected hardware
and firmware for systems such as commercial laptop, desktop or server
computers; these use cases generally match acknowledged market
segments possible for RISC-V based platforms.

In order for a platform to be compliant with OSPS, it must be compliant
with a specific use case.  That may allow it to be compliant with other
use cases, but it is recommended that a platform have one specific target
to start from.  For any given use case, all mandatory requirement must be
implemented in the platform.  Optional requirements may or may not be
implemented on any given platform; if such a requirement
could cause the platform to behave differently when not implemented,
a fallback position is specified that must be implemented.

Over time, it is expected that each use case will see a series of
revisions.  Under ideal circumstances, a platform will be compliant
with the most recent version of any use case specification.  When a
platform indicates it is compliant with the OSPS, it should specify
a use case *and* a specific revision of that use case.

// terms and definitions
include::terms.adoc[]

// bibliography
include::references.adoc[]

WARNING: what follows are original notes that will be replaced over time.

## User-Level Platform

* User-mode environments must implement at least version 2.2 of the RISC-V User
  ISA specification, which can be found at
  https://github.com/riscv/riscv-isa-manual/blob/master/release/riscv-spec-v2.2.pdf.  
* User-mode programs may not execute the `fence.i` instruction.
* User-mode environments may provide additional ISA extensions, but if those
  extensions add user-visible state they must be initially disabled.
* Within main-memory regions, aligned instruction fetch must be atomic, up to
  the smaller of ILEN and XLEN bits.  In particular, if an aligned 4-byte word
  is stored with the `sw` instruction, then any processor attempts to execute
  that word, the processor either fetches the newly stored word, or some previous
  value stored to that location.  (That is, the fetched instruction is not an
  unpredictable value, nor is it a hybrid of the bytes of the old and new
  values.)

## Supervisor-Level Platform

* Supervisor-mode environments must implement at least version 0.2.0 of the
  RISC-V SBI specification, which can be found at
  https://github.com/riscv/riscv-sbi-doc/blob/v0.2.0/riscv-sbi.adoc
* Supervisor-mode environments must implement the Sv39 page-based
  virtual-memory scheme.   Systems that support Sv48 must support Sv39, systems
  that support Sv57 must support Sv48, and so forth.
* Unless otherwise specified by a given I/O device, I/O regions are at least
  point-to-point strongly ordered.  All devices attached to a given PCIe root
  complex are on the same ordered channel (numbered 2 or above), though
  different root complexes might not be on the same ordering channel.
* On RV64I-based Unix-class systems the negative virtual addresses are reserved
  for the kernel.
* External devices (DMA engines, the debug unit, non RISC-V cores, etc) that
  are visible to RISC-V harts must appear as coherent agents, just like any
  RISC-V hart would.  If additional ordering constraints are necessary for a
  device to function, those will be provide by a device-specific mechanism.

## Machine-Level Platform

## Profiles

### Portable UNIX Platform Profile

* Supervisor-mode environments must implement RV64GC.
